### ISSUE TITLE
Initial Pipeline Run failing in CodeBuild

### ISSUE THREAD

**Issue by arnabaws15** [aws-samples/aws-cross-account-cicd-pipeline#29]
I am not sure what is going wrong here.

```
[Container] 2022/11/08 19:00:43 Running command npm run cdk synth
> my-pipeline@0.1.0 cdk /codebuild/output/src720320611/src
> cdk "synth"
/codebuild/output/src720320611/src/node_modules/aws-cdk/lib/index.js:12413
home = path.join((os.userInfo().homedir ?? os.homedir()).trim(), ".cdk");
^
SyntaxError: Unexpected token '?'
at wrapSafe (internal/modules/cjs/loader.js:915:16)
at Module._compile (internal/modules/cjs/loader.js:963:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/codebuild/output/src720320611/src/node_modules/aws-cdk/bin/cdk.js:3:15)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-pipeline@0.1.0 cdk: `cdk "synth"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-pipeline@0.1.0 cdk script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2022-11-08T19_00_44_272Z-debug.log
[Container] 2022/11/08 19:00:44 Command did not exit successfully npm run cdk synth exit status 1
```

**Comment by arnabaws15** [comment]
It appears this is a known issue with ARM Linux image v2.0 that CodeBuild uses. I had to update the file lib/pipeline-stack.ts to add a command in the section for cdkBuild. Here is a snippet of what it looks like:
`install: {
            commands: [
              'n 14.8.0',
              'npm install'
            ],
          },`
I chose v14.8.0 since the workshop talks about using this in the pre-requisites.
